apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: zookeeper
          resources:
            limits:
              memory: 512Mi
              cpu: 600m
            requests:
              memory: 256Mi
              cpu: 300m
