apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init-topics
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: kafka-init-topics
        image: bitnami/kafka:3.6.2
        command:
        - sh
        - -c
        - |
          kafka-topics.sh --create --bootstrap-server kafka.dev.svc.cluster.local:9092 --topic example-topic --partitions 1 --replication-factor 1
          kafka-topics.sh --create --bootstrap-server kafka.dev.svc.cluster.local:9092 --topic test-topic --partitions 1 --replication-factor 1
      restartPolicy: OnFailure
