apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.9.2
        resources:
          limits:
            memory: 512Mi
            cpu: 600m
          requests:
            memory: 256Mi
            cpu: 300m
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          valueFrom:
            configMapKeyRef:
              name: zookeeper-config
              key: ALLOW_ANONYMOUS_LOGIN
