apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6.2
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_ID
            - name: KAFKA_CFG_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CFG_LISTENERS
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CFG_ZOOKEEPER_CONNECT
            - name: ALLOW_PLAINTEXT_LISTENER
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: ALLOW_PLAINTEXT_LISTENER
            # - name: KAFKA_CFG_SASL_ENABLED_MECHANISMS
            #   valueFrom:
            #     configMapKeyRef:
            #       name: kafka-config
            #       key: KAFKA_CFG_SASL_ENABLED_MECHANISMS
            # - name: KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: kafka-config
            #       key: KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL
            # - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            #   valueFrom:
            #     configMapKeyRef:
            #       name: kafka-config
            #       key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            # - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            #   valueFrom:
            #     configMapKeyRef:
            #       name: kafka-config
            #       key: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            # - name: KAFKA_CFG_SASL_JAAS_CONFIG
            #   valueFrom:
            #     secretKeyRef:
            #       name: kafka-secret
            #       key: KAFKA_CFG_SASL_JAAS_CONFIG
          volumeMounts:
            - name: kafka-volume
              mountPath: /vol/db
  volumeClaimTemplates:
    - metadata:
        name: kafka-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
