apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: kafka
          resources:
            limits:
              cpu: 200m
              memory: 512Gi
            requests:
              cpu: 100m
              memory: 256Mi
