apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: set_resources.yaml

configMapGenerator:
  - name: redpanda-console-config
    envs:
      - config.env

secretGenerator:
  - name: redpanda-console-secret
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
