daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
        - type: container
          paths:
            - /var/log/containers/*.log
          processors:
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                  - logs_path:
                      logs_path: "/var/log/containers/"
            - drop_event:
                when:
                  not:
                    equals:
                      kubernetes.namespace: "alpha"
            - drop_event:
                when:
                  not:
                    regexp:
                      kubernetes.container.name: ".*"

      filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: ${NODE_NAME}
            templates:
              - condition:
                  equals:
                    kubernetes.namespace: "alpha"
                config:
                  - type: container
                    paths:
                      - /var/log/containers/*-${data.kubernetes.container.id}.log
                    processors:
                      - drop_event:
                          when:
                            not:
                              regexp:
                                kubernetes.container.name: ".*"
                      - drop_event:
                          when:
                            not:
                              equals:
                                stream: "stdout"

      output.logstash:
        hosts: ["logstash-logstash:5044"]
