apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  replicas: 1
  dataVolumeCapacity: 10Gi
  configOverrides:
    server:
      - offsets.topic.replication.factor=2
      - transaction.state.log.replication.factor=1
      - transaction.state.log.min.isr=1
      - default.replication.factor=2
      - min.insync.replicas=1
      - auto.create.topics.enable=true
  podTemplate:
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  dependencies:
    zookeeper:
      endpoint: zookeeper.kafka.svc.cluster.local:2182
      tls:
        enabled: true
