apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpha

resources:
  - ../../base

patches:
  - path: set_resources.yaml

configMapGenerator:
  - name: zookeeper-config
    envs:
      - config.env

secretGenerator:
  - name: zookeeper-secret
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
