apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: components

resources:
  - ../../base
  - pvc.yaml

configMapGenerator:
  - name: postgres-config
    envs:
      - config.env

secretGenerator:
  - name: postgres-secret
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
