apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 15Gi
  listeners:
    listeners:
    custom:
      - name: sasl
        port: 9094
        authentication:
          type: plain
          jaasConfig:
            secretRef: kafka-secret
        tls:
          enabled: false
  podTemplate:
    tolerations:
      - key: "app.stateful/component"
        operator: "Equal"
        value: "kafka-broker"
        effect: NoSchedule
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: "app.stateful/component"
                  operator: In
                  values:
                    - "kafka-broker"
    envVars:
      - name: KAFKA_HEAP_OPTS
        value: "-Xmx2G -Xms2G"
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 512Mi
