apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpha

resources:
  - ../../base

patches:
  - path: set_resources.yaml

configMapGenerator:
  - envs:
      - config.env
    name: rabbitmq-config

secretGenerator:
  - envs:
      - secret.env
    name: rabbitmq-secret

generatorOptions:
  disableNameSuffixHash: true
