# Do not use Kong Ingress Controller
ingressController:
  enabled: false

image:
  repository: kong/kong-gateway
  tag: "3.8.0.0"

# Mount the secret created earlier
secretVolumes:
  - kong-partner-cluster-cert

env:
  # data_plane nodes do not have a database
  role: data_plane
  database: "off"

  # Tell the data plane how to connect to the control plane
  cluster_control_plane: kong-cp-partner-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-partner-kong-clustertelemetry.kong.svc.cluster.local:8006

  # Configure control plane / data plane authentication
  lua_ssl_trusted_certificate: /etc/secrets/kong-partner-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-partner-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-partner-cluster-cert/tls.key

# Enterprise functionality
enterprise:
  enabled: true

# The data plane handles proxy traffic only
proxy:
  enabled: true

# These roles are served by the kong-cp deployment
admin:
  enabled: false

manager:
  enabled: false
