ingressController:
  enabled: true
  env:
    publish_service: kong/kong-dp-system-kong-proxy
    kong_admin_token: Inari1234

image:
  repository: kong/kong-gateway
  tag: "3.8.0.0"

# Mount the secret created earlier
secretVolumes:
  - kong-system-cluster-cert

env:
  # This is a control_plane node
  role: control_plane
  # These certificates are used for control plane / data plane communication
  cluster_cert: /etc/secrets/kong-system-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-system-cluster-cert/tls.key

  admin_gui_url: https://kong-admin-system-alpha.inari-th.com
  admin_gui_api_url: https://kong-admin-api-system-alpha.inari-th.com

  # Database
  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: kong
  pg_host: postgres.data-tools.svc.cluster.local

  # Kong Manager password
  password: Inari1234

# Enterprise functionality
enterprise:
  enabled: true

# The control plane serves the Admin API
admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

# Clustering endpoints are required in hybrid mode
cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002

# These roles will be served by different Helm releases
proxy:
  enabled: false
