apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
spec:
  replicas: 1
  template:
    metadata:
      labels:
        env: alpha
    spec:
      containers:
        - name: redpanda-console
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
